/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

import java.util.TreeSet;

/**
 *
 * @author Ulises
 */
public class DeTodoSA extends javax.swing.JFrame {
    public static TreeSet<Producto> productos = new TreeSet<>();
        
    /**
     * Creates new form DeTodoSA
     */
    public DeTodoSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuConsultaNombre = new javax.swing.JMenuItem();
        menuConsultarPrecio = new javax.swing.JMenuItem();
        menuConsultarRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        menuAdministracion.setText("Administración");

        menuAdmin.setText("Gestión de productos");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuAdmin);

        jMenuBar1.add(menuAdministracion);

        jMenu3.setText("Consultas");

        menuConsultaNombre.setText("Por nombre");
        menuConsultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaNombreActionPerformed(evt);
            }
        });
        jMenu3.add(menuConsultaNombre);

        menuConsultarPrecio.setText("Por precio");
        menuConsultarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarPrecioActionPerformed(evt);
            }
        });
        jMenu3.add(menuConsultarPrecio);

        menuConsultarRubro.setText("Por rubro");
        menuConsultarRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarRubroActionPerformed(evt);
            }
        });
        jMenu3.add(menuConsultarRubro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaConsultaNombre vcn = new VistaConsultaNombre();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_menuConsultaNombreActionPerformed

    private void menuConsultarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaConsultaPrecio vcn = new VistaConsultaPrecio();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_menuConsultarPrecioActionPerformed

    private void menuConsultarRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarRubroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaConsultaRubro vcn = new VistaConsultaRubro();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_menuConsultarRubroActionPerformed

    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaAdmin vcn = new VistaAdmin();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_menuAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        cargarProductosIniciales();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdmin;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenuItem menuConsultaNombre;
    private javax.swing.JMenuItem menuConsultarPrecio;
    private javax.swing.JMenuItem menuConsultarRubro;
    // End of variables declaration//GEN-END:variables

    private static void cargarProductosIniciales(){
        productos.add(new Producto(233, "Pan Dulce Marmolado x 400grs", 2572.87, 100, "Comestibles"));
        productos.add(new Producto(433, "Detergente 1L", 3500.0, 130, "Limpieza"));
        productos.add(new Producto(23, "Pan Dulce Con Frutas x 400grs", 2000.0, 100, "Comestibles"));
        productos.add(new Producto(23, "Budin x 400grs", 3000.0, 100, "Comestibles"));
        productos.add(new Producto(53, "Galletas x 400grs", 6000.0, 100, "Comestibles"));
        productos.add(new Producto(1223, "Crackers x 400grs", 1500.0, 100, "Comestibles"));
        productos.add(new Producto(900, "Desodorante x 265grs", 5600.0, 100, "Perfumeria"));
    }
}
